name: CI Build BarSysInfo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    
    - name: Install dependencies
      run: dotnet restore ./src/barsysinfo/barsysinfo.sln
    
    - name: Build
      run: dotnet build ./src/barsysinfo/barsysinfo.sln --configuration Release --no-restore

    - name: Public
      run: dotnet publish ./src/barsysinfo/barsysinfo.csproj --configuration Release --output ./output
    
    - name: Display Files from Output
      run: ls -R
      working-directory: ./output

    - uses: actions/upload-artifact@v2
      with:
        name: barsysinfo.zip
        path: ./output/**/
        if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn` 
